### ISSUE TITLE
CFFI: change & to addressof

### ISSUE THREAD

**Issue by rbrewer123** [CausalityLtd/pony-tutorial#33]
The CFFI section talks about `&` but it seems that `addressof` is what is actually currently used.

**Comment by andymcn** [comment]
Yes, the language syntax has changed and we haven't updated the tutorial yet. We'll get round to it in due course, or please feel free to submit a fix yourself!

**Comment by rurban** [comment]
Fixed with 7747e986eefa9935afe871dac8b7e8f3916ede97
