### ISSUE TITLE
Tutorial doesn't mention ISize and USize types

### ISSUE THREAD

**Issue by jkleiser** [CausalityLtd/pony-tutorial#34]

**Comment by jkleiser** [comment]
And sandbox.ponylang.org doesn't understand ISize (and probably not USize).

**Comment by jonas-l** [comment]
I think both tutorial and sandbox are updated to match latest released version. Which is now [0.2.1][releases] and there are [quite a few features undocumented in tutorial and unavailable in sandbox][enhancements-after-0-2-1].

[releases]: https://github.com/CausalityLtd/ponyc/releases
[enhancements-after-0-2-1]: https://github.com/CausalityLtd/ponyc/issues?q=is%3Aissue+is%3Aclosed+closed%3A%3E2015-10-06+label%3Aenhancement

**Comment by jkleiser** [comment]
From the description under "Built-in primitive types" here
http://tutorial.ponylang.org/types/primitives.html
it is easy to understand what types like I8 and U8 mean, but ISize, ILong, USize and ULong are not that obvious to me.
On of the Guiding Principles of the tutorial is this:

> Fully defined semantics. The semantics of all language features must be available in the standard language docs. It is not acceptable to leave behaviour undefined or "implementation dependent".

A few words should be all it takes to explain ISize, ILong, USize and ULong.

**Comment by SeanTAllen** [comment]
Those are actually Guiding principles for Pony not specifically the tutorial. 

Are you able to issue a PR for ISize, ILong etc?

**Comment by jkleiser** [comment]
No, I'm sorry.

**Comment by jkleiser** [comment]
I just issued a PR for this. Thanks to Joe Eli McIlvain. ;-)
